config/routes.rb
Rails.application.routes.draw do
  get 'comic_books/index'
  get 'comic_books/show'
  root 'home#index'
  
  get 'home/index'
  get 'home/about'
  
  get 'characters/search', to: 'characters#search', as: 'character_search'
  get 'publishers/:id/characters', to: 'publishers#characters', as: 'publisher_characters'
  get 'publishers/:id/comic_books', to: 'publishers#comic_books', as: 'publisher_comic_books'
  
  resources :characters, only: [:index, :show]
  resources :publishers, only: [:index, :show] do
    resources :comic_books, only: [:index]
  end

  resources :comic_books, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :publisher

  validates :name, presence: true, uniqueness: true
end

app/models/comic_book.rb
class ComicBook < ApplicationRecord
  belongs_to :publisher

  validates :name, presence: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :characters
    has_many :comic_books

    validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.page(params[:page]).per(10)
  end

  def show
    @character = Character.find(params[:id])
    @publisher = @character.publisher
  end

  def search
    if params[:query].present?
      @characters = Character.where("name LIKE ?", "%#{params[:query]}%").page(params[:page]).per(10)
    else
      @characters = Character.page(params[:page]).per(10)
    end

    if @characters.empty?
      flash.now[:notice] = "No characters found."
    end
  end
  
end

app/controllers/comic_books_controller.rb
class ComicBooksController < ApplicationController
  def index
    @comic_books = ComicBook.page(params[:page]).per(30)
  end

  def show
    @comic_book = ComicBook.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @characters = Character.page(params[:page]).per(10)
  end

  def about
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.page(params[:page]).per(10)
  end

  def show
    @publisher = Publisher.find(params[:id])
  end
  def characters
    @publisher = Publisher.find(params[:id])
    @characters = @publisher.characters.page(params[:page]).per(10)
  
    render 'characters', locals: { characters: @characters }
  end
  
  def comic_books
    @publisher = Publisher.find(params[:id])
    @comic_books = @publisher.comic_books.page(params[:page]).per(10)
  
    render 'comic_books', locals: { comic_books: @comic_books }
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/award_winners_helper.rb
module AwardWinnersHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/comic_books_helper.rb
module ComicBooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/characters/index.html.erb
    <%= render 'shared/menu' %>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Thumbnail</th>
                <th>Name</th>
                <th>Deck</th>
            </tr>
        </thead>
        <tbody>
            <% @characters.each do |character| %>
            <tr>
                <td><img src="<%= character.image_thumb %>" alt="<%= character.name %> Thumbnail"></td>
                <td><%= link_to character.name, character_path(character), style: "text-decoration: none;" %></td>
                <td><%= character.deck %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

<%= paginate @characters %>
</div>

app/views/characters/search.html.erb
    <%= render 'shared/menu' %>
<div class="container">
    <% @characters.each do |character| %>
  <div class="d-flex flex-column align-items-center">
    <p>Results found based on your search:</p>
    <ul>
        <li>
            <%= link_to character.name, character_path(character), style: "text-decoration: none;" %>
        </li>
    </ul>
    
  </div>
<% end %>

<%= paginate @characters %>

<% if flash[:notice].present? %>
  <div class="alert alert-info text-center">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>
</div>

app/views/characters/show.html.erb
    <%= render 'shared/menu' %>

    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto">
            <h1 class="mb-4"><%= @character.name %></h1>
            <p class="mb-3">Deck: <%= @character.deck %></p>
            <p class="mb-3">Origin: <%= @character.origin %></p>
            <p class="mb-3">Publisher: <%= link_to @publisher.name, publisher_characters_path(@publisher), class: "btn btn-primary mb-2" %></p>
            <img src="<%= @character.image_small %>" alt="<%= @character.name %> Small image" class="img-fluid">
            </div>
        </div>
    </div>

app/views/comic_books/index.html.erb
    <%= render 'shared/menu' %>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            <% @comic_books.each do |comic_book| %>
            <tr>
                <td><%= comic_book.id %></td>
                <td><%= link_to comic_book.name, comic_book_path(comic_book), style: "text-decoration: none;" %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

<%= paginate @comic_books %>
</div>

app/views/comic_books/show.html.erb
    <%= render 'shared/menu' %>

     <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto">
            <h1 class="mb-4"><%= @comic_book.name %></h1>
            <p class="mb-3">Publisher: <%= link_to @comic_book.publisher.name, publisher_path(@comic_book.publisher) %></p>
            </div>
        </div>
    </div>

app/views/home/about.html.erb
    <%= render 'shared/menu' %>

    <div class="container">
    <h1>About AnimeWorld</h1>

    <p>AnimeWorld is a website that provides a dataset of comic characters and publishers.</p>

    <p>Dataset Formats:</p>
    <ul>
        <li>Characters: JSON</li>
        <li>Publishers: JSON</li>
    </ul>

    <p>Data Sources:</p>
    <ul>
        <li>Characters: <a href="https://comicvine.gamespot.com/api/characters/?api_key=7e24bc3842ca1a7a8613c14172b484c34f988e62&format=json">https://comicvine.gamespot.com/api/characters/?api_key=7e24bc3842ca1a7a8613c14172b484c34f988e62&format=json</a></li>
        <li>Publishers: <a href="https://comicvine.gamespot.com/api/publishers/?api_key=7e24bc3842ca1a7a8613c14172b484c34f988e62&format=json">https://comicvine.gamespot.com/api/publishers/?api_key=7e24bc3842ca1a7a8613c14172b484c34f988e62&format=json</a></li>
    </ul>

    <p>Description:</p>
    <p>
        The Characters dataset contains information about comic characters, including their name, origin, description, and more details. The Publishers dataset provides information about publishers, including their name, description, and other info. By combining these datasets, AnimeWorld has created a database that contains character details along with their publisher's details.
    </p>

    <p>Faker Comic_Books:</p>
    <p>
        AnimeWorld also includes a Comic Book table, where comic books published by each publishers are enlisted using the Faker gem.
    </p>
    <p>Relationships:</p>
    <ul>
        <li>One Publisher has many Characters (One-to-Many: One Publisher, Many Characters)</li>
        <li>One Publisher has many ComicBooks (One-to-Many: One Publisher, Many ComicBooks)</li>
        <li>Each Character belongs to a Publisher (Many-to-One: Many Characters, One Publisher)</li>
        <li>Each ComicBook belongs to a Publisher (Many-to-One: Many ComicBooks, One Publisher)</li>
    </ul>
    <div class="text-center">
        <img src="<%= asset_path('IntroToRailsERD.jpg') %>" alt="ERD Image">
    </div>
    <p>Created by: Md Mahamudun Alam Mahin</p>
    </div>

app/views/home/index.html.erb
    <%= render 'shared/menu' %>
    <div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Thumbnail</th>
                <th>Name</th>
                <th>Deck</th>
            </tr>
        </thead>
        <tbody>
            <% @characters.each do |character| %>
            <tr>
                <td><img src="<%= character.image_thumb %>" alt="<%= character.name %> Thumbnail"></td>
                <td><%= link_to character.name, character_path(character), style: "text-decoration: none;" %></td>
                <td><%= character.deck %></td>
            </tr>
            <% end %>
        </tbody>
    </table>

    <%= paginate @characters %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeWorld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/publishers/characters.html.erb
    <%= render 'shared/menu' %>
<div class="container">
    <% if characters.present? %>
  <h2>Characters by <%= @publisher.name %></h2>
  <ul>
    <% characters.each do |character| %>
      <li>
        <%= link_to character.name, character_path(character) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="text-center">
        No characters found.
    </div>
<% end %>

</div>

app/views/publishers/comic_books.html.erb
    <%= render 'shared/menu' %>
<div class="container">
    <% if comic_books.present? %>
  <h2>Comic Books by <%= @publisher.name %></h2>
  <ul>
    <% comic_books.each do |comic_book| %>
      <li>
        <%= link_to comic_book.name, comic_books_show_path(comic_book) %>
      </li>
    <% end %>
  </ul>
<% else %>
    <div class="text-center">
        No comic books found.
    </div>
<% end %>
</div>

app/views/publishers/index.html.erb
    <%= render 'shared/menu' %>

    <div class="container">
        <div class="row">
            <% @publishers.each do |publisher| %>
            <div class="col-lg-4 mb-4">
                <div class="card h-100">
                <img src="<%= publisher.image_thumb %>" class="card-img-top" alt="<%= publisher.name %> Thumbnail">
                <div class="card-body d-flex flex-column">
                    <h2 class="card-title"><%= link_to publisher.name, publisher_path(publisher), style: "text-decoration: none;" %></h2>
                    <p class="card-text"><%= publisher.deck %></p>
                    <p>Number of Characters: <%= publisher.characters.count %></p>
                    <p>Number of Comic Books: <%= publisher.comic_books.count %></p>
                    <div class="mt-auto d-flex flex-column justify-content-end">
                        <%= link_to "Show Characters", publisher_characters_path(publisher), class: "btn btn-primary mb-2" %>
                        <%= link_to "Show Comic Books", publisher_comic_books_path(publisher), class: "btn btn-primary" %>
                    </div>
                </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    <div>
        <%= paginate @publishers %>
    </div>

app/views/publishers/show.html.erb
    <%= render 'shared/menu' %>

    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto">
            <h1 class="mb-4"><%= @publisher.name %></h1>
            <p class="mb-3">Deck: <%= @publisher.deck %></p>
            <img src="<%= @publisher.image_small %>" alt="<%= @publisher.name %> Small image" class="img-fluid">
            </div>
        </div>
    </div>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= home_index_path %>">AnimeWorld</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= home_index_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= home_about_path %>">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= characters_path %>">Characters</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= publishers_path %>">Publishers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= comic_books_index_path %>">Comic Books</a>
        </li>
      </ul>
      <form class="d-flex" method="GET" action="<%= character_search_path %>">
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>